#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check staged files
npx lint-staged

# Run type checking
yarn type:check

# Run unit tests for changed files
yarn test:unit --passWithNoTests --findRelatedTests --bail